---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./democratic-csi.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./itzg-minecraft-charts.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./rook-ceph.yaml
  - ./stakater.yaml
