---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./nzbget/ks.yaml
