apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:SM9QS/BFK5bWVZXTMZ6n4fkGz/pKkvmqB1NgqSycCiY8VsAk6ozUfOwQXgkDdlVt0ffNHnY+9l9jEfLtCuCHK+S6QG999JlC67bSdJLjcPKoDyrCLxicK7gPvXkbjA==,iv:AnLi1FcKGh9Nrnuv/Z4NJFbS3ePiUZQDAimk4LTQNrk=,tag:Faet9IkgBqc1yFPhwkD7Ng==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Oe+3OLRASCPPv5g=,iv:v7BMDkRV1/u6UCOG4hAXZ4HGY33lTLNOCWYQXWWpq1s=,tag:M1osmqGFKZvSqgTq7K+Mzg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:s1KxSM8sRFu/WqAPecEyJCtk,iv:ttxB+BaJvafZmaxtFbX656ciMrvEluKXYLk9ckmf0x8=,tag:bJ/VoIGYipeqy9nY1vXwyQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:WVQA/gQT+G77u4fRNWWr+mKz3NlAH0o7Iwl0gaE1imDA8tbe,iv:ViBWZp7a+w27hCRW/OZK5LByLJw5hAT/8BsKh3HeAnU=,tag:F3904XJd1jU1KRVpHuqH8A==,type:str]
    SECRET_CSI_USER_PW: ENC[AES256_GCM,data:SzMNuDrm7yBkby72r/M=,iv:Slgli7UWjVlrqF7Qt1QEfRX9wChtSJ751k8G1FzNq1Y=,tag:x28Wx11XRjJ2ltiT6U6oAA==,type:str]
    SECRET_HOPERESTORED_APIKEY: ENC[AES256_GCM,data:T2JGlH6ip4qLyXGpkFsaz3+2hpjwLwEohLWzIvFsFEQw4Ssj9j+c8Ch85AzCr5n46xpkQ8sDAUvtzQ3dMpcjIdEp,iv:YMKoHfuOZmDOfDOSo+X06kQETN/FBPLRBpOBLj6QCfU=,tag:xAE4kH7kAce6DIEutrfD9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age152jlmwv75v9htehsuprmwd3nmfr4kzqd6lpjgnk8juunpps6349spxehnj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZVJOTWlnbGdLREo5WE9S
            QllsdTlLNVB1S29QOGFSN2JraG1RRVJURGc0Cm9LbGF1dXREYU9paHI3UnlLbTl3
            THg3K1FvcVQydUV1MXhqZkIrZ0s4dUEKLS0tIGhhUWdod0h4UU5oR3JxYnR0TXpC
            Y0RNZ3lWVU1ueGJBRzJIaVR5NjRRVE0KN0YZegEwhow83lxwI831WcSS8bSu0UWM
            hLwR3Nj5Ktm4eXzRW/Z8B/xNWdgJQFphsdfdApkqxa5Rixi3odKY8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-22T18:25:13Z"
    mac: ENC[AES256_GCM,data:xdimqAF+CtZ56PuGGmQBPAuXMupvgKS4t2OP2rPiMG2sdKg5HtTppgU/gbnjuuU3liPFwWWQKkJ7WMg9+0//+pIIfpvuVxwbB++7P5UWX+NALIEkdbnX0DZ3c9RqY1Rgsr0vtsu3V4DDN11TlCGLpMunyANpmTkW/FrQBzkY3z0=,iv:0MiUp5PjI+rcMPwcrYSP4eOHdpOp8MhUXB5OXx1n/Rg=,tag:IKME4j8QFpWKjj+2WCm7YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
